(cl:defpackage dolly_action_msgs-msg
  (:use )
  (:export
   "<AMRDOCKACTION>"
   "AMRDOCKACTION"
   "<AMRDOCKACTIONFEEDBACK>"
   "AMRDOCKACTIONFEEDBACK"
   "<AMRDOCKACTIONGOAL>"
   "AMRDOCKACTIONGOAL"
   "<AMRDOCKACTIONRESULT>"
   "AMRDOCKACTIONRESULT"
   "<AMRDOCKFEEDBACK>"
   "AMRDOCKFEEDBACK"
   "<AMRDOCKGOAL>"
   "AMRDOCKGOAL"
   "<AMRDOCKRESULT>"
   "AMRDOCKRESULT"
  ))

