; Auto-generated. Do not edit!


(cl:in-package dolly_action_msgs-msg)


;//! \htmlinclude amrDockResult.msg.html

(cl:defclass <amrDockResult> (roslisp-msg-protocol:ros-message)
  ((docked
    :reader docked
    :initarg :docked
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass amrDockResult (<amrDockResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <amrDockResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'amrDockResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dolly_action_msgs-msg:<amrDockResult> is deprecated: use dolly_action_msgs-msg:amrDockResult instead.")))

(cl:ensure-generic-function 'docked-val :lambda-list '(m))
(cl:defmethod docked-val ((m <amrDockResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dolly_action_msgs-msg:docked-val is deprecated.  Use dolly_action_msgs-msg:docked instead.")
  (docked m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <amrDockResult>) ostream)
  "Serializes a message object of type '<amrDockResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'docked) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <amrDockResult>) istream)
  "Deserializes a message object of type '<amrDockResult>"
    (cl:setf (cl:slot-value msg 'docked) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<amrDockResult>)))
  "Returns string type for a message object of type '<amrDockResult>"
  "dolly_action_msgs/amrDockResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'amrDockResult)))
  "Returns string type for a message object of type 'amrDockResult"
  "dolly_action_msgs/amrDockResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<amrDockResult>)))
  "Returns md5sum for a message object of type '<amrDockResult>"
  "a3ad9bbe144e1b2c5d7cff122465aa06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'amrDockResult)))
  "Returns md5sum for a message object of type 'amrDockResult"
  "a3ad9bbe144e1b2c5d7cff122465aa06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<amrDockResult>)))
  "Returns full string definition for message of type '<amrDockResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool docked~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'amrDockResult)))
  "Returns full string definition for message of type 'amrDockResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool docked~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <amrDockResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <amrDockResult>))
  "Converts a ROS message object to a list"
  (cl:list 'amrDockResult
    (cl:cons ':docked (docked msg))
))
