; Auto-generated. Do not edit!


(cl:in-package dolly_action_msgs-msg)


;//! \htmlinclude amrDockFeedback.msg.html

(cl:defclass <amrDockFeedback> (roslisp-msg-protocol:ros-message)
  ((dist_to_pallet
    :reader dist_to_pallet
    :initarg :dist_to_pallet
    :type cl:float
    :initform 0.0))
)

(cl:defclass amrDockFeedback (<amrDockFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <amrDockFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'amrDockFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dolly_action_msgs-msg:<amrDockFeedback> is deprecated: use dolly_action_msgs-msg:amrDockFeedback instead.")))

(cl:ensure-generic-function 'dist_to_pallet-val :lambda-list '(m))
(cl:defmethod dist_to_pallet-val ((m <amrDockFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dolly_action_msgs-msg:dist_to_pallet-val is deprecated.  Use dolly_action_msgs-msg:dist_to_pallet instead.")
  (dist_to_pallet m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <amrDockFeedback>) ostream)
  "Serializes a message object of type '<amrDockFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'dist_to_pallet))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <amrDockFeedback>) istream)
  "Deserializes a message object of type '<amrDockFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'dist_to_pallet) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<amrDockFeedback>)))
  "Returns string type for a message object of type '<amrDockFeedback>"
  "dolly_action_msgs/amrDockFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'amrDockFeedback)))
  "Returns string type for a message object of type 'amrDockFeedback"
  "dolly_action_msgs/amrDockFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<amrDockFeedback>)))
  "Returns md5sum for a message object of type '<amrDockFeedback>"
  "bf332c4cd7d1f3d307d37e1a19b0c83e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'amrDockFeedback)))
  "Returns md5sum for a message object of type 'amrDockFeedback"
  "bf332c4cd7d1f3d307d37e1a19b0c83e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<amrDockFeedback>)))
  "Returns full string definition for message of type '<amrDockFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 dist_to_pallet~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'amrDockFeedback)))
  "Returns full string definition for message of type 'amrDockFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 dist_to_pallet~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <amrDockFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <amrDockFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'amrDockFeedback
    (cl:cons ':dist_to_pallet (dist_to_pallet msg))
))
