std_msgs/Header header_dolly

string status_of_camera

geometry_msgs/Vector3 left_corners
geometry_msgs/Vector3 right_corners
geometry_msgs/Vector3 point

bool dolly_found 
float64 corners_distance 

std_msgs/Header header_pallet_detection

string message 

geometry_msgs/Vector3 left_pocket
geometry_msgs/Vector3 right_pocket
geometry_msgs/Vector3 center_point

bool pallet_found
float64 pallet_angle