// Generated by gencpp from file dolly_action_msgs/amrDockResult.msg
// DO NOT EDIT!


#ifndef DOLLY_ACTION_MSGS_MESSAGE_AMRDOCKRESULT_H
#define DOLLY_ACTION_MSGS_MESSAGE_AMRDOCKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dolly_action_msgs
{
template <class ContainerAllocator>
struct amrDockResult_
{
  typedef amrDockResult_<ContainerAllocator> Type;

  amrDockResult_()
    : docked(false)  {
    }
  amrDockResult_(const ContainerAllocator& _alloc)
    : docked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _docked_type;
  _docked_type docked;





  typedef boost::shared_ptr< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> const> ConstPtr;

}; // struct amrDockResult_

typedef ::dolly_action_msgs::amrDockResult_<std::allocator<void> > amrDockResult;

typedef boost::shared_ptr< ::dolly_action_msgs::amrDockResult > amrDockResultPtr;
typedef boost::shared_ptr< ::dolly_action_msgs::amrDockResult const> amrDockResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dolly_action_msgs::amrDockResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dolly_action_msgs::amrDockResult_<ContainerAllocator1> & lhs, const ::dolly_action_msgs::amrDockResult_<ContainerAllocator2> & rhs)
{
  return lhs.docked == rhs.docked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dolly_action_msgs::amrDockResult_<ContainerAllocator1> & lhs, const ::dolly_action_msgs::amrDockResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dolly_action_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3ad9bbe144e1b2c5d7cff122465aa06";
  }

  static const char* value(const ::dolly_action_msgs::amrDockResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3ad9bbe144e1b2cULL;
  static const uint64_t static_value2 = 0x5d7cff122465aa06ULL;
};

template<class ContainerAllocator>
struct DataType< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dolly_action_msgs/amrDockResult";
  }

  static const char* value(const ::dolly_action_msgs::amrDockResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool docked\n"
;
  }

  static const char* value(const ::dolly_action_msgs::amrDockResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.docked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct amrDockResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dolly_action_msgs::amrDockResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dolly_action_msgs::amrDockResult_<ContainerAllocator>& v)
  {
    s << indent << "docked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.docked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOLLY_ACTION_MSGS_MESSAGE_AMRDOCKRESULT_H
