// Auto-generated. Do not edit!

// (in-package dolly_action_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class amrDockGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.reached_point = null;
      this.pallet_idx = null;
    }
    else {
      if (initObj.hasOwnProperty('reached_point')) {
        this.reached_point = initObj.reached_point
      }
      else {
        this.reached_point = false;
      }
      if (initObj.hasOwnProperty('pallet_idx')) {
        this.pallet_idx = initObj.pallet_idx
      }
      else {
        this.pallet_idx = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type amrDockGoal
    // Serialize message field [reached_point]
    bufferOffset = _serializer.bool(obj.reached_point, buffer, bufferOffset);
    // Serialize message field [pallet_idx]
    bufferOffset = _serializer.string(obj.pallet_idx, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type amrDockGoal
    let len;
    let data = new amrDockGoal(null);
    // Deserialize message field [reached_point]
    data.reached_point = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [pallet_idx]
    data.pallet_idx = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.pallet_idx);
    return length + 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dolly_action_msgs/amrDockGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2830bc314db18f6470bab1f24c955ab8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    ## Reached Coordinates ##
    
    bool reached_point
    string pallet_idx
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new amrDockGoal(null);
    if (msg.reached_point !== undefined) {
      resolved.reached_point = msg.reached_point;
    }
    else {
      resolved.reached_point = false
    }

    if (msg.pallet_idx !== undefined) {
      resolved.pallet_idx = msg.pallet_idx;
    }
    else {
      resolved.pallet_idx = ''
    }

    return resolved;
    }
};

module.exports = amrDockGoal;
