; Auto-generated. Do not edit!


(cl:in-package dolly_action_msgs-msg)


;//! \htmlinclude amrDockGoal.msg.html

(cl:defclass <amrDockGoal> (roslisp-msg-protocol:ros-message)
  ((reached_point
    :reader reached_point
    :initarg :reached_point
    :type cl:boolean
    :initform cl:nil)
   (pallet_idx
    :reader pallet_idx
    :initarg :pallet_idx
    :type cl:integer
    :initform 0))
)

(cl:defclass amrDockGoal (<amrDockGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <amrDockGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'amrDockGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dolly_action_msgs-msg:<amrDockGoal> is deprecated: use dolly_action_msgs-msg:amrDockGoal instead.")))

(cl:ensure-generic-function 'reached_point-val :lambda-list '(m))
(cl:defmethod reached_point-val ((m <amrDockGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dolly_action_msgs-msg:reached_point-val is deprecated.  Use dolly_action_msgs-msg:reached_point instead.")
  (reached_point m))

(cl:ensure-generic-function 'pallet_idx-val :lambda-list '(m))
(cl:defmethod pallet_idx-val ((m <amrDockGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dolly_action_msgs-msg:pallet_idx-val is deprecated.  Use dolly_action_msgs-msg:pallet_idx instead.")
  (pallet_idx m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <amrDockGoal>) ostream)
  "Serializes a message object of type '<amrDockGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'reached_point) 1 0)) ostream)
  (cl:let* ((signed (cl:slot-value msg 'pallet_idx)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <amrDockGoal>) istream)
  "Deserializes a message object of type '<amrDockGoal>"
    (cl:setf (cl:slot-value msg 'reached_point) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'pallet_idx) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<amrDockGoal>)))
  "Returns string type for a message object of type '<amrDockGoal>"
  "dolly_action_msgs/amrDockGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'amrDockGoal)))
  "Returns string type for a message object of type 'amrDockGoal"
  "dolly_action_msgs/amrDockGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<amrDockGoal>)))
  "Returns md5sum for a message object of type '<amrDockGoal>"
  "43f04e9c3ca80aa3d24bcb32ea9ec9f1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'amrDockGoal)))
  "Returns md5sum for a message object of type 'amrDockGoal"
  "43f04e9c3ca80aa3d24bcb32ea9ec9f1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<amrDockGoal>)))
  "Returns full string definition for message of type '<amrDockGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%## Reached Coordinates ##~%~%bool reached_point~%int32 pallet_idx~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'amrDockGoal)))
  "Returns full string definition for message of type 'amrDockGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%## Reached Coordinates ##~%~%bool reached_point~%int32 pallet_idx~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <amrDockGoal>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <amrDockGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'amrDockGoal
    (cl:cons ':reached_point (reached_point msg))
    (cl:cons ':pallet_idx (pallet_idx msg))
))
