#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'turtlebot4-tests==1.0.2','console_scripts','ros_tests'
__requires__ = 'turtlebot4-tests==1.0.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('turtlebot4-tests==1.0.2', 'console_scripts', 'ros_tests')()
    )
